askcompany/urls.py
from django.contrib import admin
from django.conf import settings
#from django.conf.urls.static import static
# from django.http import HttpResponseRedirect
from django.urls import include, path
from django.shortcuts import redirect

def root(request):
    # TO DO : URL reverse 기능
    # return HttpResponseRedirect('/blog/')
    return redirect('shop:index')


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('blog/', include('blog.urls')),
    path('shop/', include('shop.urls')),
    path('', root),
]


if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

#    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from django.urls import register_converter

from blog.views import index, hello_times
from blog.views import articles_by_year
from blog.views import naver_realtime_keywords
from blog.views import naver_blog_search

from blog.converters import FourDigitYearConverter
from blog.converters import SlugUnicodeConverter

register_converter(FourDigitYearConverter, 'year')
register_converter(SlugUnicodeConverter, 'slug_unicode')

app_name = 'blog' # URL reverse 기능에서 사용

urlpatterns = [
    path('articles/<year:year>/', articles_by_year),

    # re_path('^blog/1/$', post_detail),
    # re_path('^blog/1/edit/$', post_edit),

    path('hello_times/<int:times>/', hello_times),
    path('', index),
    path('naver/네이버실검', naver_realtime_keywords),
    path('naver/블로그검색', naver_blog_search),
]

shop/urls.py
from django.urls import path
from shop import views

app_name = 'shop'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:pk>/', views.shop_detail, name='shop_detail'),
    path('new/', views.shop_new, name='shop_new'),
    path('new_cbv/', views.shop_new_cbv, name='shop_new_cbv'),
    path('edit/<int:pk>/', views.shop_edit, name='shop_edit'),
    path('edit_cbv/<int:pk>/', views.shop_edit_cbv, name='shop_edit_cbv'),
    path('delete/<int:pk>/', views.shop_delete),
]

shop/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse

# Create your models here.
class ShopInfo(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    # photo = models.ImageField(blank=True)
    desc = models.TextField(blank=True)
    address = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        # return "/shop/{}/".format(self.id)
        return reverse("shop:shop_detail", args=[self.id])
        # return reverse("shop:shop_detail", kwargs={'pk': self.id})

class Item(models.Model):
    shop = models.ForeignKey(ShopInfo, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    desc = models.TextField(blank=True)
    price = models.PositiveIntegerField()
    is_public = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

shop/forms.py
from django import forms
from .models import ShopInfo

class ShopForm(forms.ModelForm):
    class Meta:
        model = ShopInfo
        # fields = '__all__'  # 모든 필드 가져오기
        fields = ['name', 'desc', 'address']  # 지정 필드만 가져오기 ('photo')

shop/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView, ListView, DetailView, DeleteView
from .models import ShopInfo
from .forms import ShopForm


# Create your views here.
# def index(request):
#     # 전체 shop 목록을 가져올 예정이다.
#     qs = ShopInfo.objects.all()
#     return render(request, 'shop/shop_list.html', {
#         'shop_list':qs,
#     })

# index = PostListView.as_view()

# class PostListView(ListView):
#     model = ShopInfo

#     def get_context_data(self):
#         context = super().get_context_data()
#         context.update({
#             'hello': 'world',
#         })
#         return context

# def shop_detail(request, pk):
#     shop = ShopInfo.objects.get(pk=pk) # 즉시 DB에서 가져옴
#     return render(request, 'shop/shop_detail.html', {
#         'shop':shop,
#     })

@login_required
def shop_new(request):
    form_cls = ShopForm

    if request.method == "POST":
        form = form_cls(request.POST, request.FILES)
        if form.is_valid():
            shop = form.save(commit=False)
            shop.user = request.user
            shop.save()
            return redirect(shop)
    else:
        form = form_cls()

    return render(request, 'shop/shop_form.html', {
        'form' : form,
    })

@login_required
def shop_edit(request, pk):
#    shop = ShopInfo.objects.get(pk=pk)
    shop = get_object_or_404(ShopInfo, pk=pk)
  
    if request.user != shop.user:
        return redirect(shop)

    form_cls = ShopForm

    if request.method == "POST":
        form = form_cls(request.POST, request.FILES, instance=shop)
        if form.is_valid():
            shop = form.save()
            return redirect('/shop/{}/' .format(shop.id))
    else:
        form = form_cls(instance=shop)

    return render(request, 'shop/shop_form.html', {
        'form' : form,
    })

@login_required
def shop_delete(request, pk):
    shop = get_object_or_404(ShopInfo, pk=pk)
  
    if request.user != shop.user:
        return redirect(shop)

    if request.method == 'POST':
        shop.delete()
        return redirect('shop:index')

    return render(request, 'shop/shop_confirm_delete.html', {
        'shop': ShopInfo,
    })


# 클래스 기반으로 view, detail 함수 구현
index = ListView.as_view(model=ShopInfo,
                         context_object_name='shop_list',
                         template_name='shop/shop_list.html')

shop_detail = DetailView.as_view(model=ShopInfo,
                         context_object_name='shop',
                         template_name='shop/shop_detail.html')

# shop_delete = DeleteView.as_view(model=ShopInfo,
#                          context_object_name='shop',
#                          template_name='shop/shop_confirm_delete.html',
#                          success_url=reverse_lazy('shop:index'))

# 클래스 기반으로 new, edit 함수 구현
shop_new_cbv = CreateView.as_view(
    model=ShopInfo, form_class=ShopForm, template_name='shop/shop_form.html')

shop_edit_cbv = UpdateView.as_view(
    model=ShopInfo, form_class=ShopForm, template_name='shop/shop_form.html')

shop/templates/shop/layout.html
{% extends "layout.html" %}

{% block page_title %}
    꼉의 상점리스트
{% endblock %}

shop/templates/shop/shop_confirm_delete.html
<h1>{{ shop }}을 삭제하시겠습니까?</h1>

<form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="삭제하겠습니다."/>
</form>

shop/templates/shop/shop_detail.html
{% extends "shop/layout.html" %}

{% block content %}
    <div class="container">
        <div class="col-sm-12">
            <h1>{{ shop }}</h1>

            {{ shop.desc }} |
            {{ shop.address }}

            <hr/>
            <a href="{% url "shop:index" %}" class="btn btn-primary">목록으로</a>
            <a href="{% url "shop:shop_edit" shop.id %}" class="btn btn-success">수정</a>
            <a href="/shop/delete/{{shop.id}}" class="btn btn-danger">삭제</a>
        </div>
    </div>

{% endblock %}

shop/templates/shop/shop_form.html
<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <table>
        {{ form }}
    </table>
    <input type="submit" />
</form>

shop/templates/shop/shop_list.html
{% extends "shop/layout.html" %}

{% block content %}
    <div class="container">
        <div class="card-group">
            {% for shop in shop_list %}
                <div class="col-sm-4 mb-3">
                    <div class="card">
                        <img src="http://newsimg.hankookilbo.com/2016/04/13/201604131460701467_1.jpg" class="card-img-top" alt="...">
                        <div class="card-body">
                        <h5 class="card-title">
                            <a href="{% url "shop:shop_detail" shop.id %}">
                                #{{ shop.id }}. {{ shop.name }}
                            </a>
                        </h5>
                        {% if shop.address %}
                        <p class="card-text">
                            {{ shop.address }}
                        {% endif %}
                        {% if shop.desc %}
                        <p class="card-text">
                            {{ shop.desc }}
                        </p>
                        {% endif %}
                        <p class="card-text">
                        <small class="text-muted">
                            {{ shop.created_at }}
                        </small>
                        </p>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>

        <a href="{% url "shop:shop_new" %}" class="btn btn-primary">새 가게 등록 </a>
   
    </div>

{% endblock %}